blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='home'),
    path('<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo')
]

home/urls.py
from django.contrib import admin
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

# HTTP Request <-> HTTP Reponse
# MVT (MVC)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('home.urls')), 
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from blog.data import posts
from typing import Any
from django.http import HttpRequest, Http404
# importando a json da api, que tranformei em list de dict

# Create your views here.
def blog(request):

    context = {
        'text':'Olá blog',
        'posts': posts
    }

    return render(request, 'blog/index.html', context)

def exemplo(request):

    context = {
        'text':'Olá exemplo',
        'title':'Essa é uma página de exemplo - ',
    }

    return render(request, 'blog/exemplo.html', context)

def post(request:HttpRequest, post_id:int):
    found_post: dict[str, Any] | None = None

    for post in posts:
       if post['id'] == post_id:
           found_post = post
           break

    if found_post is None:
        raise Http404('Post não existe.')

    context = {
        'post':found_post,
        'title': found_post['title'] + ' - ',
    }

    return render(request, 'blog/post.html', context)

home/views.py
from django.shortcuts import render

# Create your views here
def home(request):
    context = {
        'text':'Olá home',
    }
    return render(request, 'home/index.html', context)

blog/templates/blog/exemplo.html
{% extends 'global/base.html' %}
   
{% block texto %} {{text}} {% endblock texto %}

blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
    {% for post in posts %}
        {% include 'global/partials/postblock.html' %} 
    {% endfor %}
{% endblock posts %}
    

blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
    <article class="post single-post">
         <header>
             <h1 class="post__title">
                 <a href="{% url 'blog:post' post.id %}">
                     {{ post.title }}
                </a>
             </h1>
         </header>
         <div class="post__body">{{ post.body }}</div>
</article>

{% endblock posts %}
    

home/templates/home/index.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block home %} <h1>HOME</h1> {% endblock home %}